# Generated by Django 2.0.2 on 2018-05-22 21:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarks',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='bookmarks',
            name='url',
            field=models.URLField(default='', unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='bookmarks',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookmarks',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
